#!/usr/bin/env bash

set -eo pipefail

readonly alpha_ip="10.70.26.96"
readonly zeta_ip="10.70.26.88"
readonly alpha_nfs_dir="/media/alpha/4648e5ef-4c93-4b66-bb2f-c2fcf00c9cae/nfs/kubernetes"

readonly dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

bold() {
    echo "$(tput bold)$1$(tput sgr0)"
}

export_common_env() {
}

install() {
    local files=$1

    export PLSWORK_KUBERNETES_MASTER_IP="${alpha_ip}"
    export PLSWORK_KUBEADM_TOKEN="h3jajt.vz9z4uxxrw310p45" # Generated with `kubeadm token generate`.
    export PLSWORK_INGRESS_HTTP_PORT="80"
    export PLSWORK_INGRESS_HTTPS_PORT="443"
    export PLSWORK_NFS_DIR="${alpha_nfs_dir}"
    export PLSWORK_NFS_EXPORT_HOST="*"
    export PLSWORK_NFS_SERVER="${alpha_ip}"

    for file in "${files[@]}" ; do
        echo
        bold "##############################################################################"
        bold "    ${file}"
        bold "##############################################################################"
        echo
        ${dir}/${file}
    done
}

install_master() {
    export PLSWORK_KUBERNETES_MASTER=1

    local files=()
    files+=( "install/rp_filtering.sh" )
    files+=( "install/apt.sh" )
    files+=( "install/docker.sh" )
    files+=( "install/kubernetes_node.sh" )
    files+=( "install/helm.sh" )
    files+=( "install/kubernetes_ingress.sh" )
    files+=( "install/nfs.sh" )

    install $files
}

install_node() {
    local files=()
    files+=( "install/rp_filtering.sh" )
    files+=( "install/rp_filtering.sh" )
    files+=( "install/apt.sh" )
    files+=( "install/docker.sh" )
    files+=( "install/kubernetes_node.sh" )
    files+=( "install/helm.sh" )

    install $files
}

install_polyaxon() {
    local files=()
    files+=( "install/polyaxon_cert_manager.sh" )
    files+=( "install/polyaxon.sh" )

    install $files
}

usage() {
    echo "Usage:"
    echo "  $0 [flags]"
    echo "  $0 [command]"
    echo
    echo "Available Commands:"
    echo "  help        Help for $0.
    echo "  master      Provision Kubernetes master node."
    echo "  node        Provision Kubernetes node."
    echo "  polyaxon    Install Polyaxon on current Kubernetes cluster."
    echo
    echo "Flags:"
    echo "  -h, --help    Help for $0.
    echo
}

if [ $# -ne 1 ] ; then
    echo "error: expected single argument but have $#" >&2
    exit 1
fi

command=""

while [ $# -gt 0 ] ; do
    case "$1" in
        help|--help|-h) usage ; exit 0 ;;
        master|node|polyaxon) command="$1" ;;
        *) echo "error: unknown flag/command $1" >&2 ; usage ; exit 1;;
    esac
    shift
done

case $command in
    master) install_master ;;
    node) install_node ;;
    polyaxon) install_polyaxon ;;
    *) echo "error: unknown value for master $master" >&2 ; usage ; exit 1 ;;
esac
